https:
  host: "0.0.0.0"
  port: "8082"
  read-timeout: "30000"
  

api:
  autodiscovery: "19072055"
  
  
keystore:
  path: "certs/server-keystore.jks"
  type: "JKS"
  
  
truststore:
  path: "certs/server-truststore.jks"
  type: "JKS"