#%RAML 1.0 DataType
type: object
properties:
  firstname:
      type: string
      required: true
      description: First name
  lastname:
      type: string
      required: true
      description: Last name
  id:
      type: string
      required: true
      description: Id
  address:
      type: string
      required: false
      description: Address